version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      patch:
        applies-to: version-updates
        update-types:
          - "patch"
      minor:
        applies-to: version-updates
          - "minor"
